all:
  children:
    alpine_web:
      hosts:
        psst-prod:
          ansible_host: "2001:bc8:711:4da5:dc00:1ff:fe0f:fc23"
          ansible_user: "ttauveron"
          ansible_become: true
          ansible_become_method: su
          ansible_become_user: root
